spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}

sentry:
  dsn: ${SENTRY_AUTH_TOKEN}
  traces-sample-rate: 1.0